'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'screens',
      [
        {
          id: 1,
          name: 'Bandeja de entrada',
          description: 'Pantalla de bandeja de entrada',
          path: '/inbox-view',
          icon: 'lucide:inbox',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 2,
          name: 'Chat multi-canal',
          description: 'Pantalla de chat multi canal',
          path: '/inbox-multi-channel',
          icon: 'streamline-ultimate:corporate-social-media',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 3,
          name: 'Correo electrónico',
          description: 'Pantalla de correo electrónico',
          path: '/mail',
          icon: 'lucide:mail',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 4,
          name: 'Reportes',
          description: 'Pantalla de reportes',
          path: '/reports',
          icon: 'lucide:chart-line',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 5,
          name: 'Campañas',
          description: 'Pantalla de campañas',
          path: '/campaigns',
          icon: 'lucide:megaphone',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 6,
          name: 'Audio',
          description: 'Pantalla de campañas de audio',
          path: '/campaigns/audio-campaign',
          icon: null,
          parent_id: 5,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 7,
          name: 'SMS',
          description: 'Pantalla de campañas de sms',
          path: '/campaigns/sms-campaign',
          icon: null,
          parent_id: 5,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 8,
          name: 'Correo',
          description: 'Pantalla de campañas de sms',
          path: '/campaigns/mail-campaign',
          icon: null,
          parent_id: 5,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 9,
          name: 'plantillas',
          description: 'Pantalla de plantillas',
          path: '/templates',
          icon: 'eos-icons:templates',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 10,
          name: 'Mis plantillas',
          description: 'Pantalla de mis plantillas',
          path: '/templates/my-templates',
          icon: null,
          parent_id: 9,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 11,
          name: 'gestión atención asesor',
          description: 'Pantalla de gestión atención asesor',
          path: '/adviser',
          icon: 'fluent:people-call-24-regular',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 12,
          name: 'dashboard asesor',
          description: 'Pantalla de dashboard asesor',
          path: '/adviser/dashboard-adviser',
          icon: null,
          parent_id: 11,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 13,
          name: 'Teléfono',
          description: 'Pantalla de teléfono',
          path: '/adviser/phone',
          icon: null,
          parent_id: 11,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 14,
          name: 'Chat',
          description: 'Pantalla de chat',
          path: '/adviser/chat',
          icon: null,
          parent_id: 11,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 15,
          name: 'Cartera',
          description: 'Pantalla de cartera',
          path: '/portfolios',
          icon: 'lucide:briefcase',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 16,
          name: 'Supervisor',
          description: 'Pantalla de supervisor',
          path: '/supervisor',
          icon: 'mingcute:user-add-line',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 17,
          name: 'Asignaciones',
          description: 'Pantalla de asignaciones',
          path: '/assignments',
          icon: 'lucide:bookmark-check',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 18,
          name: 'Llamadas',
          description: 'Pantalla de llamadas',
          path: '/calls',
          icon: 'lucide:phone',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 19,
          name: 'Ajustes',
          description: 'Pantalla de ajustes',
          path: '/settings',
          icon: 'lucide:bolt',
          parent_id: null,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 20,
          name: 'Configuración de la cuenta',
          description: 'Pantalla de configuración de la cuenta',
          path: '/settings/general',
          icon: 'lucide:briefcase',
          parent_id: 19,
          status: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 21,
          name: 'Roles',
          description:
            'Los roles definen los niveles de acceso y permisos que tiene cada usuario dentro del sistema. Esto permite organizar el trabajo del equipo y mantener la seguridad de la cuenta.',
          path: '/settings/roles',
          icon: 'lucide:shield-plus',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 22,
          name: 'Usuarios',
          description: 'Pantalla de usuarios',
          path: '/settings/users',
          icon: 'lucide:square-user-round',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 23,
          name: 'Áreas',
          description:
            'Las áreas administrativas permiten organizar a los usuarios según su unidad de trabajo. Esta estructura facilita la distribución de responsabilidades, la asignación de mensajes y el seguimiento eficiente de la atención ciudadana, según la especialidad o jurisdicción de cada área.',
          path: '/settings/departments',
          icon: 'lucide:building-2',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 24,
          name: 'Oficinas',
          description:
            'Las oficinas representan los espacios físicos o virtuales desde los cuales se brinda atención a los ciudadanos. Permiten organizar el trabajo según ubicación o jurisdicción, y se pueden asociar a áreas administrativas y usuarios responsables.',
          path: '/settings/offices',
          icon: 'lucide:building',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 25,
          name: 'Equipos',
          description:
            'Los equipos agrupan a usuarios que colaboran en la atención y gestión de mensajes dentro del sistema. Facilitan la organización del trabajo según funciones, especialidades o procesos, y permiten una mejor coordinación entre miembros asignados a tareas comunes.',
          path: '/settings/teams',
          icon: 'lucide:users',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 26,
          name: 'Habilidades',
          description:
            'Las habilidades identifican conocimientos o competencias específicas de los usuarios, como idiomas, normativas o tipos de trámites. Sirven para asignar solicitudes de forma más precisa, asegurando que cada caso sea atendido por personal capacitado.',
          path: '/settings/skills',
          icon: 'lucide:stars',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 27,
          name: 'Canales',
          description:
            'Los canales de atención son los medios a través de los cuales los ciudadanos se comunican con la entidad, como correo electrónico, chat, redes sociales o formularios web. Permiten centralizar y gestionar los mensajes recibidos desde distintas plataformas en un solo sistema.',
          path: '/settings/channels',
          icon: 'lucide:inbox',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 28,
          name: 'Estados personalizados',
          description: 'Pantalla de estados personalizados',
          path: '/settings/states',
          icon: 'lucide:tag',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 29,
          name: 'Respuestas predefinidas',
          description: 'Pantalla de respuestas predefinidas',
          path: '/settings/predefined-response',
          icon: 'ph:chat-circle-dots',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 30,
          name: 'Mensajes Automáticos',
          description: 'Pantalla de mensajes automáticos',
          path: '/settings/automatic-messages',
          icon: 'tabler:message',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 31,
          name: 'Etiquetas',
          description: 'Pantalla de etiquetas',
          path: '/settings/tags',
          icon: 'lucide:bookmark',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 32,
          name: 'Recordatorio',
          description:
            'Los recordatorios te ayudan a organizar y dar seguimiento a tareas importantes dentro de tu flujo de atención. Puedes crear un recordatorio para un contacto o una conversación, especificando la fecha, hora y una breve descripción. Desde el panel lateral, puedes ver todos los recordatorios asignados y marcar aquellos que ya han sido atendidos. Esto garantiza que ninguna tarea quede pendiente y mejora la eficiencia de tu equipo.',
          path: '/settings/reminder',
          icon: 'lucide:watch',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 33,
          name: 'Calendario',
          description: 'Pantalla de calendario',
          path: '/settings/calendar',
          icon: 'solar:calendar-linear',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 34,
          name: 'Feriados',
          description: 'Pantalla de calendario',
          path: '/settings/holidays',
          icon: 'solar:calendar-linear',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 35,
          name: 'Horario de canales',
          description: 'Asignación de horarios de canales',
          path: '/settings/channel-schedule',
          icon: 'lucide:calendar-days',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 36,
          name: 'monitoring-panel',
          description: 'Pantalla de información de comunicaciones',
          path: '/settings/monitoring-panel',
          icon: 'lucide:chart-bar-big',
          parent_id: 19,
          status: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
