'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'screens',
      [
        {
          id: 1,
          name: 'Bandeja de entrada',
          description: 'Pantalla de bandeja de entrada',
          url: '/inbox-view',
          icon: 'lucide:inbox',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 2,
          name: 'Chat multi-canal',
          description: 'Pantalla de chat multi canal',
          url: '/inbox-multi-channel',
          icon: 'streamline-ultimate:corporate-social-media',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3,
          name: 'conversaciones',
          description: 'Pantalla de conversaciones',
          url: '/conversations',
          icon: 'lucide:message-circle',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 4,
          name: 'todas las conversaciones',
          description: 'Pantalla de todas las conversaciones',
          url: '/conversations/dashboard',
          icon: null,
          idParent: 3,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 5,
          name: 'menciones',
          description: 'Pantalla de menciones',
          url: '/conversations/mentions',
          icon: null,
          idParent: 3,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 6,
          name: 'desatendido',
          description: 'Pantalla de desatendido',
          url: '/conversations/unattended',
          icon: null,
          idParent: 3,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          name: 'Reportes',
          description: 'Pantalla de reportes',
          url: '/reports',
          icon: 'lucide:chart-line',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 8,
          name: 'campañas',
          description: 'Pantalla de campañas',
          url: '/campaigns',
          icon: 'lucide:megaphone',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9,
          name: 'Gestionar Campañas',
          description: 'Pantalla de campañas',
          url: '/campaigns/campaings-management',
          icon: null,
          idParent: 8,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // {
        //   id: 9,
        //   name: 'live chat',
        //   description: 'Pantalla de campañas',
        //   url: '/campaigns/live-chat',
        //   icon: null,
        //   idParent: 8,
        //   status: true,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        {
          id: 10,
          name: 'sms',
          description: 'Pantalla de campañas',
          url: '/campaigns/sms',
          icon: null,
          idParent: 8,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 11,
          name: 'Correo',
          description: 'Pantalla de campañas por correo',
          url: '/campaigns/email',
          icon: null,
          idParent: 8,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 12,
          name: 'plantillas',
          description: 'Pantalla de plantillas',
          url: '/templates',
          icon: 'eos-icons:templates',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 13,
          name: 'Mis plantillas',
          description: 'Pantalla de mis plantillas',
          url: '/templates/my-templates',
          icon: null,
          idParent: 12,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 14,
          name: 'gestión atención asesor',
          description: 'Pantalla de gestión atención asesor',
          url: '/adviser',
          icon: 'fluent:people-call-24-regular',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 15,
          name: 'dashboard asesor',
          description: 'Pantalla de dashboard asesor',
          url: '/adviser/dashboard-adviser',
          icon: null,
          idParent: 14,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 16,
          name: 'Teléfono',
          description: 'Pantalla de teléfono',
          url: '/adviser/telefono',
          icon: null,
          idParent: 14,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 17,
          name: 'Chat',
          description: 'Pantalla de chat',
          url: '/adviser/chat',
          icon: null,
          idParent: 14,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 18,
          name: 'Cartera',
          description: 'Pantalla de cartera',
          url: '/briefcase',
          icon: 'lucide:briefcase',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 19,
          name: 'Supervisor',
          description: 'Pantalla de supervisor',
          url: '/supervisor',
          icon: 'mingcute:user-add-line',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 20,
          name: 'Asignaciones',
          description: 'Pantalla de asignaciones',
          url: '/assignments',
          icon: 'lucide:bookmark-check',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 21,
          name: 'Ajustes',
          description: 'Pantalla de ajustes',
          url: '/settings',
          icon: 'lucide:bolt',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 22,
          name: 'Configuración de la cuenta',
          description: 'Pantalla de configuración de la cuenta',
          url: '/settings/general',
          icon: 'lucide:briefcase',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 23,
          name: 'Roles',
          description:
            'Los roles definen los niveles de acceso y permisos que tiene cada usuario dentro del sistema. Esto permite organizar el trabajo del equipo y mantener la seguridad de la cuenta.',
          url: '/settings/roles',
          icon: 'lucide:shield-plus',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 24,
          name: 'Usuarios',
          description: 'Pantalla de usuarios',
          url: '/settings/usuarios',
          icon: 'lucide:square-user-round',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 25,
          name: 'Áreas',
          description:
            'Las áreas administrativas permiten organizar a los usuarios según su unidad de trabajo. Esta estructura facilita la distribución de responsabilidades, la asignación de mensajes y el seguimiento eficiente de la atención ciudadana, según la especialidad o jurisdicción de cada área.',
          url: '/settings/areas',
          icon: 'lucide:building-2',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 26,
          name: 'Oficinas',
          description:
            'Las oficinas representan los espacios físicos o virtuales desde los cuales se brinda atención a los ciudadanos. Permiten organizar el trabajo según ubicación o jurisdicción, y se pueden asociar a áreas administrativas y usuarios responsables.',
          url: '/settings/oficinas',
          icon: 'lucide:building',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 27,
          name: 'Equipos',
          description:
            'Los equipos agrupan a usuarios que colaboran en la atención y gestión de mensajes dentro del sistema. Facilitan la organización del trabajo según funciones, especialidades o procesos, y permiten una mejor coordinación entre miembros asignados a tareas comunes.',
          url: '/settings/teams',
          icon: 'lucide:users',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 28,
          name: 'Habilidades',
          description:
            'Las habilidades identifican conocimientos o competencias específicas de los usuarios, como idiomas, normativas o tipos de trámites. Sirven para asignar solicitudes de forma más precisa, asegurando que cada caso sea atendido por personal capacitado.',
          url: '/settings/skills',
          icon: 'lucide:stars',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 29,
          name: 'Canales',
          description:
            'Los canales de atención son los medios a través de los cuales los ciudadanos se comunican con la entidad, como correo electrónico, chat, redes sociales o formularios web. Permiten centralizar y gestionar los mensajes recibidos desde distintas plataformas en un solo sistema.',
          url: '/settings/inboxes',
          icon: 'lucide:inbox',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 30,
          name: 'Estados personalizados',
          description: 'Pantalla de estados personalizados',
          url: '/settings/status',
          icon: 'lucide:tag',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 31,
          name: 'Respuestas predefinidas',
          description: 'Pantalla de respuestas predefinidas',
          url: '/settings/predefined-response',
          icon: 'ph:chat-circle-dots',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 32,
          name: 'Mensajes Automáticos',
          description: 'Pantalla de mensajes automáticos',
          url: '/settings/mensajes-automaticos',
          icon: 'tabler:message',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 33,
          name: 'Etiquetas',
          description: 'Pantalla de etiquetas',
          url: '/settings/labels',
          icon: 'lucide:bookmark',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 34,
          name: 'Recordatorio',
          description: 'Pantalla de recordatorio',
          url: '/settings/reminder',
          icon: 'lucide:watch',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 35,
          name: 'Calendario',
          description: 'Pantalla de calendario',
          url: '/settings/calendar',
          icon: 'solar:calendar-linear',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 36,
          name: 'Llamadas',
          description: 'Pantalla de llamadas',
          url: '/calls',
          icon: 'lucide:phone',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 37,
          name: 'Feriados',
          description: 'Pantalla de feriados',
          url: '/settings/feriados',
          icon: 'solar:calendar-linear',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 38,
          name: 'Mail',
          description: 'Pantalla de Mail',
          url: '/mails',
          icon: 'lucide:mail',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 39,
          name: 'Asignación de Horarios',
          description: 'Asignación de Horarios',
          url: '/schedule-assignment',
          icon: 'lucide:mail',
          idParent: null,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 40,
          name: 'monitoring-panel',
          description: 'Pantalla de información de comunicaciones',
          url: '/settings/monitoring-panel',
          icon: 'lucide:chart-bar-big',
          idParent: 21,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
